# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/weinijuan/cpu/IP/xilinx_ip/sram_128x64/sram_128x64.xci
# IP: The module: 'sram_128x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/weinijuan/cpu/IP/xilinx_ip/sram_128x64/sram_128x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_128x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/weinijuan/cpu/IP/xilinx_ip/sram_128x64/sram_128x64.xci
# IP: The module: 'sram_128x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/weinijuan/cpu/IP/xilinx_ip/sram_128x64/sram_128x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_128x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
