#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Aug 15 11:19:03 CST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6c1fb159a8da46e296128ad1578aae5d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L fifo_generator_v13_2_5 -L axi_interconnect_v1_7_17 -L blk_mem_gen_v8_4_4 -L axi_infrastructure_v1_1_0 -L axi_clock_converter_v2_1_19 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot soc_top_behav xil_defaultlib.soc_top xil_defaultlib.glbl -log elaborate.log"
xelab -wto 6c1fb159a8da46e296128ad1578aae5d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L fifo_generator_v13_2_5 -L axi_interconnect_v1_7_17 -L blk_mem_gen_v8_4_4 -L axi_infrastructure_v1_1_0 -L axi_clock_converter_v2_1_19 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot soc_top_behav xil_defaultlib.soc_top xil_defaultlib.glbl -log elaborate.log

