# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/weinijuan/cpu/IP/xilinx_ip/sram_32x52bit/sram_32x52bit.xci
# IP: The module: 'sram_32x52bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/weinijuan/cpu/IP/xilinx_ip/sram_32x52bit/sram_32x52bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_32x52bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/weinijuan/cpu/IP/xilinx_ip/sram_32x52bit/sram_32x52bit.xci
# IP: The module: 'sram_32x52bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/weinijuan/cpu/IP/xilinx_ip/sram_32x52bit/sram_32x52bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_32x52bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
