// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsimu_top.h for the primary calling header

#ifndef VERILATED_VSIMU_TOP___024ROOT_H_
#define VERILATED_VSIMU_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_save.h"

class Vsimu_top__Syms;
class Vsimu_top___024unit;


class Vsimu_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vsimu_top___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(DifftestInstrCommit__02Eclock,0,0);
        VL_IN8(DifftestExcpEvent__02Eclock,0,0);
        VL_IN8(DifftestTrapEvent__02Eclock,0,0);
        VL_IN8(DifftestStoreEvent__02Eclock,0,0);
        VL_IN8(DifftestLoadEvent__02Eclock,0,0);
        VL_IN8(DifftestCSRRegState__02Eclock,0,0);
        VL_IN8(DifftestGRegState__02Eclock,0,0);
        VL_IN8(aclk,0,0);
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_awvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_wvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo_empty;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo_full;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo_full;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_prog;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_rw;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_sel_rd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_sel_wr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT3;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT6;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT8;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT9;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT10;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HIT11;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_HIT;
        VL_IN8(DifftestInstrCommit__02Ecoreid,7,0);
        VL_IN8(DifftestInstrCommit__02Eindex,7,0);
        VL_IN8(DifftestInstrCommit__02Evalid,0,0);
        VL_IN8(skip,0,0);
        VL_IN8(is_TLBFILL,0,0);
        VL_IN8(TLBFILL_index,4,0);
        VL_IN8(is_CNTinst,0,0);
        VL_IN8(wen,0,0);
        VL_IN8(wdest,7,0);
        VL_IN8(csr_rstat,0,0);
        VL_IN8(DifftestExcpEvent__02Ecoreid,7,0);
        VL_IN8(excp_valid,0,0);
        VL_IN8(eret,0,0);
        VL_IN8(DifftestTrapEvent__02Ecoreid,7,0);
        VL_IN8(DifftestTrapEvent__02Evalid,0,0);
        VL_IN8(code,2,0);
        VL_IN8(DifftestStoreEvent__02Ecoreid,7,0);
        VL_IN8(DifftestStoreEvent__02Eindex,7,0);
        VL_IN8(DifftestStoreEvent__02Evalid,7,0);
        VL_IN8(DifftestLoadEvent__02Ecoreid,7,0);
        VL_IN8(DifftestLoadEvent__02Eindex,7,0);
        VL_IN8(DifftestLoadEvent__02Evalid,7,0);
        VL_IN8(DifftestCSRRegState__02Ecoreid,7,0);
        VL_IN8(DifftestGRegState__02Ecoreid,7,0);
        VL_IN8(aresetn,0,0);
        VL_IN8(enable_delay,0,0);
        VL_OUT8(ram_ren,0,0);
        VL_OUT8(ram_wen,3,0);
        VL_OUT8(debug0_wb_rf_wen,0,0);
        VL_OUT8(debug0_wb_rf_wnum,4,0);
        VL_OUT8(open_trace,0,0);
        VL_OUT8(num_monitor,0,0);
        VL_OUT8(confreg_uart_data,7,0);
    };
    struct {
        VL_OUT8(write_uart_valid,0,0);
        VL_INOUT8(uart_rx,0,0);
        VL_INOUT8(uart_tx,0,0);
        VL_OUT8(led_rg0,1,0);
        VL_OUT8(led_rg1,1,0);
        VL_OUT8(num_csn,7,0);
        VL_OUT8(num_a_g,6,0);
        VL_IN8(__SYM__switch,7,0);
        VL_OUT8(btn_key_col,3,0);
        VL_IN8(btn_key_row,3,0);
        VL_IN8(btn_step,1,0);
        CData/*0:0*/ uart_rx__en0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu_awvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu_wvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_wready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__m0_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__m0_bresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_arready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__m0_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__m0_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__s0_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_s_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_arready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_rvalid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_s_ram_wen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__UART_RI;
        CData/*0:0*/ simu_top__DOT__soc__DOT__uart0_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__uart0_txd_oe;
        CData/*3:0*/ simu_top__DOT__soc__DOT__cpu__DOT__debug1_wb_rf_wen;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__debug1_wb_rf_wnum;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__req_inst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__cpu__DOT__wstrb_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__addr_ok_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__req_mem;
        CData/*3:0*/ simu_top__DOT__soc__DOT__cpu__DOT__wstrb_mem;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__preif_allow_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__preif_ready_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__preif_flush;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__if_allow_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__if_ready_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__id_valid_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__id_ready_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__id_allow_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__ex_valid_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__ex_allow_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__ex_flush;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__mem_valid_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__mem_ready_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__mem_flush;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__wb_valid_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__wb_flush;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__wb_allow_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__instr_temp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__zero;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__lt;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__overflow;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__unsignBranchCmp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__is_unsign_load_id;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__control__regWriteDataSel;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__control__aluctrl;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__control__alusel2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__control__alusel1;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__control__itype;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__control__pcsel;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rd_no_id;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__regWriteEn_wb;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rd_no_mem;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__memRead_ex;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alusel1_ex;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alusel2_ex;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__aluctrl_ex;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rj_no_ex;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rk_no_ex;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rd_no_ex;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__memWriteEn_ex;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__size_mem_ex;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__is_unsign_load_mem;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__memRead_mem;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__memWriteEn_mem;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__readData_temp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____VdfgTmp_h78aa7f48__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__If__DOT__pipeline_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__id__DOT__pipeline_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SUB_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SLT_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SLTU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_NOR_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_AND_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_OR_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_XOR_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SLL_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SRL_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SRA_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_MUL_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_MULH_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_MULHU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_DIV_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_MOD_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_DIVU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_MODU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SLLI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SRLI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SRAI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SLTI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_SLTUI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_ANDI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_ORI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_XORI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_LUI_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_PCADDU12I_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_LD_B_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_LD_H_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_LD_W_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_ST_B_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_ST_H_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_ST_W_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_LD_BU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_LD_HU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_JIRL_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BL_TYPE;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BEQ_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BNE_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BLT_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BGE_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BLTU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_BGEU_TYPE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_reg_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_shamt_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_regimm_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_u_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_store_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_b_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT__is_branch_inst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT____VdfgTmp_hffea2556__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT____VdfgTmp_hfa3cf28f__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__control__DOT____VdfgTmp_h9c888c86__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__forwarding__DOT__MEM_forward_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__forwarding__DOT__WB_forward_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__hazard_detect__DOT__stall;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__ex__DOT__pipeline_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__divSigned;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__divEn;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__adder_cin;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__quotient_sign;
        CData/*5:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__count;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__mem__DOT__pipeline_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__wb__DOT__pipeline_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_req;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_req_or;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_wr_r;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_size_r;
        CData/*3:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_wstrb_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__data_back;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__addr_rcv;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__wdata_rcv;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_ar_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_aw_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_no_delay;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_short_delay;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_w_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h34d16b8e__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_hb251d2f0__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h765eb7cb__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h76518f96__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h4bbe5f71__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_wready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_arready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_wready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_arready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rlast;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_data_s_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_s_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_awready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_wready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_arready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rlast;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_awvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_wvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_arvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rready;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_sel_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_sel_group_1;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__bvalid_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_sel_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_sel_group_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo_empty;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_dir_ins;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_dir_del;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_data_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_pre_sel;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_sel_reg;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_sel;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_data_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_dir_ins;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_data_pre_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_h6c6cb05b__1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hee60d8fe__1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____VdfgTmp_h58a8c0e9__0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__wr_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__rd_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__wr_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__rd_ptr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_rw_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_psel_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_enab_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_valid_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__dma_grant;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__dma_ack_i;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_psel_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_enab_cpu;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_datai_cpu;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_datao_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_word_trans_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_valid_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_clk_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_reset_n_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_ack;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_datai;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_datao;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_psel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_ready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__csr_rw_sm;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__csr_rw_sm_nxt;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_w_id;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_r_id;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_rstrb;
    };
    struct {
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_s_wstrb;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__rd_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_rd_size;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_wr_size;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_psel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_enab;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__we;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__re;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__rx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__tx2rx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__enable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__srx_pad;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ier;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__iir;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fcr;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__mcr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__infrared;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_pol;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lcr;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__start_dlc;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msi_reset;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__trigger_level;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_reset;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tx_reset;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_reg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_en_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__mode_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fi_di_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__repeat_reg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr1r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tf_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_pop;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_count;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tf_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tstate;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rstate;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__block_cnt;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__block_value;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__max_repeat_time;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__serial_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__serial_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_overrun;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_push_pulse;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____Vcellinp__receiver__enable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask_condition;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__iir_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msr_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fifo_read;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__delayed_modem_signals;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr1_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_toggle;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__d1_fifo_read;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgTmp_h84138141__0;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__counter;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__bit_counter;
        CData/*6:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__shift_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__stx_o_tmp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__parity_xor;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__bit_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tx_error;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__error_time;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_data_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_overrun;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_data_bak;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT____VdfgTmp_hd44064a5__0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__bottom;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top_plus_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__i_uart_sync_flops__DOT__flop_0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rbit_counter;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rshift;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity_error;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rframing_error;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rbit_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity_xor;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__counter_b;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_push_q;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_eq_7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_eq_0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_minus_1;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__data8_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__bottom;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top_plus_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__nand_int;
    };
    struct {
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__nand_iordy_r0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__nand_iordy_r1;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__nand_type_r1;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__nand_type_r2;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_STATE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_clr_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_DONE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_CE_;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NANDtag;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_IORDY;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_DMA_REQ;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_cmd_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__status;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_number;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__ADDR_pointer;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_ADDR_COUNT;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__WAIT_NUM;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__HOLD_NUM;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__COMMAND;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__PRE_STATE;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__READ_ID_NUM;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_GO;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_ACK;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__DMA_OP_DONE;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__ERASE_SERIAL;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__now_up_half;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__now_oob;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_h194fa2e7__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_hdb5c27a8__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_hda1c3bf2__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_he5337c8c__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_hea0d93a3__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_h2fe3549b__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT____VdfgTmp_h559fe0c2__0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arlen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arlen_last;
        CData/*2:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_en;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rcur;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_allow_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_data;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_pop;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_datas;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arlen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arlen_last;
        CData/*2:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_valid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rcur;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_allow_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_pop;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_datas;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wvalid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__confreg__DOT__confreg_uart_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__confreg_uart_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__confreg__DOT__virtual_uart_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__open_trace;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__num_monitor;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r3;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_end_r1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_end_r2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_uart_valid;
    };
    struct {
        CData/*2:0*/ simu_top__DOT__soc__DOT__confreg__DOT__state;
        CData/*2:0*/ simu_top__DOT__soc__DOT__confreg__DOT__next_state;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__key_flag;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__state_count;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_step0_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_step1_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step0_flag;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step1_flag;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__scan_data;
        CData/*2:0*/ __VdfgTmp_hcd04e225__0;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestInstrCommit__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestExcpEvent__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestTrapEvent__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestStoreEvent__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestLoadEvent__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestCSRRegState__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__DifftestGRegState__02Eclock;
        CData/*0:0*/ __Vtrigrprev__TOP__aclk;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(led,15,0);
        SData/*15:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__dlc;
        SData/*9:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__counter_t;
        SData/*8:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_cnt;
        SData/*8:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_next;
        SData/*10:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_data_in;
        SData/*9:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__toc_value;
        SData/*13:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_addr_c;
        SData/*15:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_timing;
        SData/*13:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__WRITE_MAX_COUNT;
        SData/*13:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__READ_MAX_COUNT;
        SData/*13:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__data_count;
        SData/*15:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_key_r;
        SData/*15:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_key_tmp;
        VL_IN(instr,31,0);
        VL_IN(csr_data,31,0);
        VL_IN(intrNo,31,0);
        VL_IN(cause,31,0);
        VL_IN(exceptionInst,31,0);
        VL_IN(random_seed,22,0);
        VL_OUT(ram_raddr,31,0);
        VL_IN(ram_rdata,31,0);
        VL_OUT(ram_waddr,31,0);
        VL_OUT(ram_wdata,31,0);
        VL_OUT(debug0_wb_pc,31,0);
        VL_OUT(debug0_wb_rf_wdata,31,0);
        VL_OUT(num_data,31,0);
        VL_OUTW(uart_ctr_bus,127,0,4);
        IData/*31:0*/ simu_top__DOT__soc__DOT__m0_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__debug1_wb_pc;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__debug1_wb_rf_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__wdata_inst;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__preif_data_in;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__preif_data_out;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__preif_nop;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__nextPC;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__instr_temp;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rj_id;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rk_id;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__regWriteData_wb;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__immout_id;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rj_id_true;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rk_id_true;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__aluout_mem;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__aluSrc1_ex;
    };
    struct {
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__aluSrc2_ex;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__pc_ex;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__memaddr_ex;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__aluout_ex;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__readData_temp;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__readData;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__If__DOT__pipeline_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__quotient;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__adder_result;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__adder_b;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__quotient_u;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__remainder_u;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__dividend_reg;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__dividend_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_addr_r;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_axi_interface_u__DOT__do_wdata_r;
        IData/*22:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_random;
        IData/*22:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_random_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__w_addr_dir_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_hit_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_dir_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__i;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__i;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_addr_dma;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_wdata_dma;
        IData/*23:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_high_24b_wr;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_datai;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_req_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datai_32;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datao_32;
        IData/*23:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__dl;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__REG_DAT_T;
        IData/*24:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_addr_r;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_op_num;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_parameter;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_ce_map0;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_ce_map1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_rdy_map0;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_rdy_map1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__nand_command;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_OP_NUM;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_DAT_O_RD;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_DAT_I_WR;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_araddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awaddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awaddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_araddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awaddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awaddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr0;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr3;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr4;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr5;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr6;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr7;
    };
    struct {
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_rg0_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_rg1_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__num_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer_r2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__simu_flag;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__io_simu;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_rdata_reg;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer_r1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__key_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step0_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step1_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__count;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(DifftestInstrCommit__02Epc,63,0);
        VL_IN64(timer_64_value,63,0);
        VL_IN64(wdata,63,0);
        VL_IN64(exceptionPC,63,0);
        VL_IN64(DifftestTrapEvent__02Epc,63,0);
        VL_IN64(cycleCnt,63,0);
        VL_IN64(instrCnt,63,0);
        VL_IN64(storePAddr,63,0);
        VL_IN64(storeVAddr,63,0);
        VL_IN64(storeData,63,0);
        VL_IN64(paddr,63,0);
        VL_IN64(vaddr,63,0);
        VL_IN64(crmd,63,0);
        VL_IN64(prmd,63,0);
        VL_IN64(euen,63,0);
        VL_IN64(ecfg,63,0);
        VL_IN64(estat,63,0);
        VL_IN64(era,63,0);
        VL_IN64(badv,63,0);
        VL_IN64(eentry,63,0);
        VL_IN64(tlbidx,63,0);
        VL_IN64(tlbehi,63,0);
        VL_IN64(tlbelo0,63,0);
        VL_IN64(tlbelo1,63,0);
        VL_IN64(asid,63,0);
        VL_IN64(pgdl,63,0);
        VL_IN64(pgdh,63,0);
        VL_IN64(save0,63,0);
        VL_IN64(save1,63,0);
        VL_IN64(save2,63,0);
        VL_IN64(save3,63,0);
        VL_IN64(tid,63,0);
        VL_IN64(tcfg,63,0);
        VL_IN64(tval,63,0);
        VL_IN64(ticlr,63,0);
        VL_IN64(llbctl,63,0);
        VL_IN64(tlbrentry,63,0);
        VL_IN64(dmw0,63,0);
        VL_IN64(dmw1,63,0);
        VL_IN64(gpr_0,63,0);
        VL_IN64(gpr_1,63,0);
        VL_IN64(gpr_2,63,0);
        VL_IN64(gpr_3,63,0);
        VL_IN64(gpr_4,63,0);
    };
    struct {
        VL_IN64(gpr_5,63,0);
        VL_IN64(gpr_6,63,0);
        VL_IN64(gpr_7,63,0);
        VL_IN64(gpr_8,63,0);
        VL_IN64(gpr_9,63,0);
        VL_IN64(gpr_10,63,0);
        VL_IN64(gpr_11,63,0);
        VL_IN64(gpr_12,63,0);
        VL_IN64(gpr_13,63,0);
        VL_IN64(gpr_14,63,0);
        VL_IN64(gpr_15,63,0);
        VL_IN64(gpr_16,63,0);
        VL_IN64(gpr_17,63,0);
        VL_IN64(gpr_18,63,0);
        VL_IN64(gpr_19,63,0);
        VL_IN64(gpr_20,63,0);
        VL_IN64(gpr_21,63,0);
        VL_IN64(gpr_22,63,0);
        VL_IN64(gpr_23,63,0);
        VL_IN64(gpr_24,63,0);
        VL_IN64(gpr_25,63,0);
        VL_IN64(gpr_26,63,0);
        VL_IN64(gpr_27,63,0);
        VL_IN64(gpr_28,63,0);
        VL_IN64(gpr_29,63,0);
        VL_IN64(gpr_30,63,0);
        VL_IN64(gpr_31,63,0);
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__id__data_out;
        VlWide<4>/*106:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT____Vcellout__wb__data_out;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__id__DOT__pipeline_data;
        VlWide<6>/*188:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__ex__DOT__pipeline_data;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__mul_result;
        QData/*32:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__minuend;
        QData/*32:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__minuend_shifted;
        QData/*32:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__minuend_next;
        QData/*32:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__alu__DOT__myDiv__DOT__difference;
        VlWide<3>/*79:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__mem__DOT__pipeline_data;
        VlWide<4>/*106:0*/ simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__wb__DOT__pipeline_data;
        QData/*37:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__addr_in_die;
        QData/*47:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__ID_INFORM;
        QData/*37:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__nand_module__DOT__NAND__DOT__NAND_ADDR;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_push_data;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_datas;
        VlUnpacked<IData/*31:0*/, 32> simu_top__DOT__soc__DOT__cpu__DOT__cpu_sram_u__DOT__rf__DOT__rf;
        VlUnpacked<CData/*3:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bid;
        VlUnpacked<CData/*1:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bresp;
        VlUnpacked<CData/*3:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rid;
        VlUnpacked<IData/*31:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rdata;
        VlUnpacked<CData/*1:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rresp;
        VlUnpacked<CData/*4:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__BASE_ADDR;
        VlUnpacked<CData/*2:0*/, 2> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__fifo_ram;
        VlUnpacked<CData/*2:0*/, 2> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__fifo_ram;
        VlUnpacked<CData/*7:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__tfifo__DOT__ram;
        VlUnpacked<CData/*2:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__fifo;
        VlUnpacked<CData/*7:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__rfifo__DOT__ram;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<8> __VactTriggered;
    VlTriggerVec<8> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vsimu_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsimu_top___024root(Vsimu_top__Syms* symsp, const char* v__name);
    ~Vsimu_top___024root();
    VL_UNCOPYABLE(Vsimu_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __Vserialize(VerilatedSerialize& os);
    void __Vdeserialize(VerilatedDeserialize& os);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
